project_name: osc-logs

builds:
  - id: default
    main: .
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64
    ldflags:
      - -s -w
    binary: osc-logs
    env:
      - CGO_ENABLED=0

archives:
  - id: tar
    format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - LICENSES/*
      - README.md
      - osc-logs

  - id: zip
    format: zip
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - LICENSES/*
      - README.md
      - osc-logs.exe

release:
  github:
    owner: OUTSCALE
    name: osc-logs
  draft: false
  prerelease: false

checksum:
  name_template: "checksums.txt"
