version = 1
SPDX-PackageName = "osc-logs"
SPDX-PackageSupplier = "Outscale support <opensource@outscale.com>"
SPDX-PackageDownloadLocation = "https://github.com/outscale/osc-logs/"

[[annotations]]
path = "**.md"
precedence = "aggregate"
SPDX-FileCopyrightText = "2026 Outscale SAS <opensource@outscale.com>"
SPDX-License-Identifier = "CC-BY-4.0"

[[annotations]]
path = ["Makefile", "**.go", "**.sum", "**.mod", ".gitignore"]
precedence = "aggregate"
SPDX-FileCopyrightText = "2026 Outscale SAS <opensource@outscale.com>"
SPDX-License-Identifier = "BSD-3-Clause"
