# .goreleaser.yml

project_name: osc-logs
builds:
  - id: default
    main: .
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - 386
      - amd64
      - arm64
    ignore:
      - goos: darwin
        goarch: 386
      - goos: windows
        goarch: arm64
    ldflags:
      - -s -w
    binary: osc-logs
    env:
      - CGO_ENABLED=0

archives:
  - format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - LICENSE
      - README.md
      - osc-logs

  - format: zip
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    replacements:
      windows: win
    files:
      - LICENSE
      - README.md
      - osc-logs.exe

release:
  github:
    owner: OUTSCALE
    name: osc-logs
  draft: false
  prerelease: false

checksum:
  name_template: 'checksums.txt'
